name: Cypress

on: [pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set Tokens
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM }} && npm config set @gsap:registry https://npm.greensock.com/ && npm config set //npm.greensock.com/:_authToken ${{ secrets.GSAP }}

      - name: Install Pnpm
        run: sudo npm -g i pnpm

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache-dir-path.outputs.STORE_PATH }}
            ~/.cache
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node Dependencies
        run: pnpm install

      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.ts
          browser: chrome
          component: true
          command: pnpm run test
          install: false
          headed: false
        env:
          NODE_ENV: test

      - name: Cypress report action
        uses: dmitry/cypress-report-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          pathname: cypress/reports/index.json