name: SecurityPipeline

on: [pull_request]

jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Running Horusec Security
      env:
        HORUSEC_CLI_HORUSEC_API_URI: ${{ secrets.HORUSEC_API }}
        HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ secrets.HORUSEC_TOKEN }}
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta
        horusec start -p="./" -e="true"